name: formation-symfony-debutant

services:
  caddy-php:
    build: caddy-php
    volumes:
      - '../..:/srv/app'
      - './caddy-php/Caddyfile:/etc/caddy/Caddyfile'
    ports:
      - 80:80
      - 443:443
      - 2019:2019
