name: Tests

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  phpunit:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Lint
        run: |
          php bin/console lint:container
          php bin/console lint:yaml config/
          php bin/console lint:twig

      - name: Lint
        run: |
          php vendor/bin/phpstan analyse src/ tests/

      - name: PHPUnit
        run: |
          php bin/console doctrine:database:create
          php bin/console doctrine:migrations:migrate
          php bin/console doctrine:fixtures:load -q
          php vendor/bin/phpunit

      - name: Composer Audit
        continue-on-error: true
        run: |
          composer audit
